scrapper:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
server:
  port: 9091
spring:
  application:
    name: Scrapper
springdoc:
  swagger-ui:
    path: /swagger-ui
logging:
  config: classpath:log4j2-plain.xml
