bot:
  token: 7796544062:AAHpPSex_nwuJUxXgl8sbcnZ8ROmFoF4MVk
server:
  port: 9090
spring:
  application:
    name: Bot
  jackson:
    time-zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui
logging:
  config: classpath:log4j2-plain.xml
